<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>fabric</name>
  <version>0.1.0</version>
  <description>A behaviour planning system based on capabilities2 system </description>

  <maintainer email="kalana.ratnayakemudiyanselage@canberra.edu.au">Kalana Ratnayake</maintainer>
  <maintainer email="kalanaratnayake@gmail.com">Kalana Ratnayake</maintainer>

  <author email="kalana.ratnayakemudiyanselage@canberra.edu.au">Kalana Ratnayake</author>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>fabric_msgs</depend>
  <depend>capabilities2_msgs</depend>
  <depend>event_logger</depend>
  <depend>event_logger_msgs</depend>
  <depend>capabilities2_utils</depend>
  <depend>tinyxml2_vendor</depend>
  <depend>backward_ros</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
