/**:
  ros__parameters:      
    validation_plugins: [fabric::CompatibilityValidation, fabric::ParameterValidation]
    parsing_plugin : fabric::XMLParser
    generation_plugin: fabric::PromptToolsGenerator
    # generation_plugin: fabric::ExperienceGenerator
    PromptToolsGenerator:
      model_family: openai
      model: gpt-5.1
      use_cache: true
      use_chat_mode: false
    capability_client:
      bond_topic: "/capabilities/bond"
      service_wait_timeout_sec: -1

