# action to transfer a plan for execution
# goal
std_msgs/Header header
string plan
---
# result
std_msgs/Header header
bool success
string message
string[] failed_elements
---
# feedback
std_msgs/Header header
string progress
