/**:
  ros__parameters:
    # plan_file_path: "install/fabric/share/fabric/plans/default.xml"
    # plan_file_path: "install/fabric/share/fabric/plans/navigation/navigation_1.xml"   # 1 point navigation example
    # plan_file_path: "install/fabric/share/fabric/plans/navigation/navigation_2.xml"   # 5 point navigation example
    # plan_file_path: "install/fabric/share/fabric/plans/navigation/navigation_3.xml"   # 5 point navigation with 1 point inaccessible (1 recoveries) example
    # plan_file_path: "install/fabric/share/fabric/plans/navigation/navigation_4.xml"   # 5 point navigation with 4 point inaccessible (4 recoveries) example
    # plan_file_path: "install/fabric/share/fabric/plans/prompt/prompt_1.xml"           # PromptCapabilityRunner Example
    # plan_file_path: "install/fabric/share/fabric/plans/prompt/prompt_2.xml"           # PromptPoseRunner Example
    # plan_file_path: "install/fabric/share/fabric/plans/prompt/prompt_3.xml"           # PromptPlanRunner Example
    plan_file_path: "install/fabric/share/fabric/plans/generative/generative_1.xml"   # Generative Example 1 - Single point navigation
    # plan_file_path: "install/fabric/share/fabric/plans/generative/generative_2.xml"   # PromptOccupancyRunner Example
    # plan_file_path: "install/fabric/share/fabric/plans/generative/generative_3.xml"   # PromptPoseRunner Example
    # plan_file_path: "install/fabric/share/fabric/plans/generative/generative_4.xml"   # PromptPlanRunner Example
    # plan_file_path: "install/fabric/share/fabric/plans/generative/generative_5.xml"   # PromptPlanRunner Example

    compatibility_validation_plugin: fabric::CompatibilityValidation
    parsing_plugin : fabric::XMLParser
    capability_client:
      bond_topic: "/capabilities/bond"

