std_msgs/Header header
string plan
---
std_msgs/Header header

# if plan_id is set it mean plan got accepted. 
# if empty (""), it got rejected.
string plan_id

# error description for rejection
string error